<a href="https://colab.research.google.com/github/machave11/Python---Data-Science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from skimage.io import imread 

# Numpy -  A multidimentional array object

In [7]:
# Generate some random data
data = np.random.randn(2,3)
print(data,'\n')
print(data * 10)

[[ 0.12640835  0.53295917 -1.04803101]
 [ 1.29565591  0.21195002  0.40591724]] 

[[  1.26408346   5.32959173 -10.48031007]
 [ 12.95655911   2.11950016   4.05917244]]


In [8]:
#Every array has a shape, a tuple indicating the size of each dimension,
# A dtype, an object describing the data type of the array:
print("data shape = ", data.shape)
print("data dtype = ", data.dtype)

data shape =  (2, 3)
data dtype =  float64


# Creating ndarrays

In [9]:
data1 = [1, 2.5, 3, 7.5, 4]
arr1 = np.array(data1)
print(arr1)
arr1

[1.  2.5 3.  7.5 4. ]


array([1. , 2.5, 3. , 7.5, 4. ])

# Nested sequences, like a list of equal-length lists, will be converted into a multidimen‐sional array:


In [10]:
data2 =[[1,2,3,4,5.5], [2.5,1.2,3.2,3,3,1.9]]
arr2 = np.array(data2)
print(arr2)
print("diamension of arr2=",arr2.ndim)
print("shape of arr2=",arr2.shape)

[list([1, 2, 3, 4, 5.5]) list([2.5, 1.2, 3.2, 3, 3, 1.9])]
diamension of arr2= 1
shape of arr2= (2,)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


In [11]:
# Zero to identity matrices
print(np.zeros(10),'\n')
print(np.zeros((3, 6)),'\n')
print(np.eye(3))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# Arange is array valued built in python range function 
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


#Data Types for ndarrays

In [13]:
arr1 = np.array([1,2,3,4], dtype=np.float64)
arr2 = np.array([1,3,2,5], dtype=np.int32)
print("data type of arr1=", arr1.dtype)
print("data type of arr2=", arr2.dtype)

data type of arr1= float64
data type of arr2= int32


In [14]:
#You can explicitly convert or cast an array from one dtype to another using ndarray’s
#astype method:
arr = np.array([1,3,4,5])
print(arr.dtype,'\n')

float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int64 

float64


In [15]:
#If I cast some floating-point numbers to be of integer dtype, the decimal part will be truncated:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr.astype(np.int32))

[ 3 -1 -2  0 12 10]


In [16]:
numeric_string = np.array(['1.23', '4.56', '5.65'])
print(numeric_string)
print(numeric_string.astype(np.float64))

['1.23' '4.56' '5.65']
[1.23 4.56 5.65]


# Arithmetic with NumPy Arrays

In [17]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print('\n',arr.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]

 float64


Arrays are important because they enable you to express batch operations on data
without writing any for loops. NumPy users call this vectorization. Any arithmetic
operations between equal-size arrays applies the operation ELEMENT-WISE:

In [18]:
print(arr * arr, '\n' )
print(arr + arr, '\n')
print(1 / arr)

[[ 1.  4.  9.]
 [16. 25. 36.]] 

[[ 2.  4.  6.]
 [ 8. 10. 12.]] 

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [19]:
#Comparisons between arrays of the same size yield boolean arrays:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

# Basic Indexing and Slicing

In [20]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print(arr)


[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [21]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[2])
print(arr2d[0][2])
print(arr2d[0,2])

[7 8 9]
3
3


#Indexing with slices

In [22]:
print(arr2d)
print()
print(arr2d[:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]]


#Transposing Arrays and Swapping Axes

In [26]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [28]:
#For higher dimensional arrays, transpose will accept a tuple of axis numbers to per‐
#mute the axes (for extra mind bending):
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [29]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])